#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" &&
  . "../utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

print_info "• Development Tools"

# CLI Tools
# brew_install "Docker" "docker" "--cask"
#b brew_install "Docker Compose" "docker-compose"
brew_install "HTTP Server" "http-server"
brew_install "Redis" "redis"
brew_install "PostgreSQL" "postgresql@14"
brew_install "PHP" "php"
brew_install "MailHog" "mailhog"
brew_install "Minio" "minio/stable/minio"
brew_install "Minio Client" "minio/stable/mc"
brew_install "LuaRocks" "luarocks"
brew_install "bash" "bash"
brew_install "bash-completion" "bash-completion"
brew_install "bat" "bat"
brew_install "composer" "composer"
brew_install "ediitorconfig" "editorconfig"
brew_install "mkcert" "mkcert"
brew_install "apr" "apr"
brew_install "apr-util" "apr-util"
brew_install "autoconf" "autoconf"
brew_install "argon2" "argon2"
brew_install "boost" "boost"
brew_install "cjson" "cjson"
brew_install "ccache" "ccache"
brew_install "clang-build-analyzer" "clang-build-analyzer"
brew_install "clang-format" "clang-format"
brew_install "cmake" "cmake"
brew_install "editorconfig" "editorconfig"
brew_install "direnv" "direnv"
brew_install "gcc" "gcc"
brew_install "gh" "gh"
brew_install "json-glib" "json-glib"
brew_install "krb5" "krb5"
brew_install "lame" "lame"
brew_install "lpeg" "lpeg"
brew_install "make" "make"
brew_install "lua" "lua"
brew_install "luajit" "luajit"
brew_install "luarocks" "luarocks"
brew_install "patchutils" "patchutils"
brew_install "pcre" "pcre"
brew_install "pcre2" "pcre2"
brew_install "perl" "perl"
brew_install "perl-build" "perl-build"
brew_install "web-ext" "web-ext"
brew_install "tree-sitter" "tree-sitter"
brew_install "uniutils" "uniutils"
brew_install "usbutils" "usbutils"
brew_install "uthash" "uthash"
brew_install "vedic" "vedic"
brew_install "prettier" "prettier"
brew_install "rbenv" "rbenv"
brew_install "ruby" "ruby"
brew_install "stylua" "stylua"
brew_install "shfmt" "shfmt"
brew_install "sqlite" "sqlite"
brew_install "tcl-tk" "tcl-tk"
brew_install "tealdeer" "tealdeer"
brew_install "the_silver_searcher" "the_silver_searcher"
brew_install "tidy-html5" "tidy-html5"
brew_install "chromedriver" "chromedriver" "--cask"

# GUI Tools
# brew_install "Visual Studio Code" "visual-studio-code" "--cask"
brew_install "iTerm 2" "iterm2@beta" "--cask"
brew_install "MacDown" "macdown" "--cask"
brew_install "color-oracle" "color-oracle" "--cask"
brew_install "color-studio" "color-studio" "--cask"
brew_install "colorsnapper" "colorsnapper" "--cask"
brew_install "colortester" "colortester" "--cask"
brew_install "colorwell" "colorwell" "--cask"
