#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" &&
  . "../utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

print_info "•  My Over the Top Font Collection"

brew_install "font-0xproto-nerd-font" "font-0xproto-nerd-font" "--cask"
brew_install "font-agave-nerd-font" "font-agave-nerd-font" "--cask"
brew_install "font-anka-coder" "font-anka-coder" "--cask"
brew_install "font-arimo-nerd-font" "font-arimo-nerd-font" "--cask"
brew_install "font-awesome-terminal-fonts" "font-awesome-terminal-fonts" "--cask"
brew_install "font-commit-mono-nerd-font" "font-commit-mono-nerd-font" "--cask"
brew_install "font-d2coding-nerd-font" "font-d2coding-nerd-font" "--cask"
brew_install "font-envy-code-r-nerd-font" "font-envy-code-r-nerd-font" "--cask"
brew_install "font-fira-code-nerd-font" "font-fira-code-nerd-font" "--cask"
brew_install "font-fontawesome" "font-fontawesome" "--cask"
brew_install "font-germania-one" "font-germania-one" "--cask"
brew_install "font-gohufont-nerd-font" "font-gohufont-nerd-font" "--cask"
brew_install "font-hasklug-nerd-font" "font-hasklug-nerd-font" "--cask"
brew_install "font-intel-one-mono" "font-intel-one-mono" "--cask"
brew_install "font-intone-mono-nerd-font" "font-intone-mono-nerd-font" "--cask"
brew_install "font-m-plus-1-code" "font-m-plus-1-code" "--cask"
brew_install "font-m-plus-1-latin" "font-m-plus-1-latin" "--cask"
brew_install "font-m-plus-1p" "font-m-plus-1p" "--cask"
brew_install "font-m-plus-2" "font-m-plus-2" "--cask"
brew_install "font-meslo-lg-nerd-font" "font-meslo-lg-nerd-font" "--cask"
brew_install "font-monaspace-nerd-font" "font-monaspace-nerd-font" "--cask"
brew_install "font-monocraft-nerd-font" "font-monocraft-nerd-font" "--cask"
brew_install "font-monofur-nerd-font" "font-monofur-nerd-font" "--cask"
brew_install "font-mononoki-nerd-font" "font-mononoki-nerd-font" "--cask"
brew_install "font-mplus-nerd-font" "font-mplus-nerd-font" "--cask"
brew_install "font-ntr" "font-ntr" "--cask"
brew_install "font-profont-nerd-font" "font-profont-nerd-font" "--cask"
brew_install "font-proggy-clean-tt-nerdfont-proggy-clean-tt-nerd-font" "-font" "--cask"
brew_install "font-rubik-80s-fade" "font-rubik-80s-fade" "--cask"
brew_install "font-rubik-beastly" "font-rubik-beastly" "--cask"
brew_install "font-rubik-broken-fax" "font-rubik-broken-fax" "--cask"
brew_install "font-rubik-doodle-shadow" "font-rubik-doodle-shadow" "--cask"
brew_install "font-rubik-doodle-trianglfont-rubik-doodle-triangles" "es" "--cask"
brew_install "font-rubik-gemstones" "font-rubik-gemstones" "--cask"
brew_install "font-rubik-glitch-pop" "font-rubik-glitch-pop" "--cask"
brew_install "font-rubik-glitch" "font-rubik-glitch" "--cask"
brew_install "font-rubik-lines" "font-rubik-lines" "--cask"
brew_install "font-rubik-maps" "font-rubik-maps" "--cask"
brew_install "font-rubik-scribble" "font-rubik-scribble" "--cask"
brew_install "font-rubik-spray-paint" "font-rubik-spray-paint" "--cask"
brew_install "font-rubik-vinyl" "font-rubik-vinyl" "--cask"
brew_install "font-rubik-wet-paint" "font-rubik-wet-paint" "--cask"
brew_install "font-sf-mono-for-powerlinfont-sf-mono-for-powerline" "e" "--cask"
brew_install "font-sf-mono" "font-sf-mono" "--cask"
brew_install "font-sf-pro" "font-sf-pro" "--cask"
brew_install "font-simple-line-icons" "font-simple-line-icons" "--cask"
brew_install "font-sn-pro" "font-sn-pro" "--cask"
brew_install "font-sudo" "font-sudo" "--cask"
brew_install "font-sue-ellen-francisco" "font-sue-ellen-francisco" "--cask"
brew_install "font-sura" "font-sura" "--cask"
brew_install "font-suranna" "font-suranna" "--cask"
brew_install "font-suravaram" "font-suravaram" "--cask"
brew_install "font-terminess-ttf-nerd-font" "font-terminess-ttf-nerd-font" "--cask"
brew_install "font-ubuntu-nerd-font" "font-ubuntu-nerd-font" "--cask"
brew_install "font-zed-mono-nerd-font" "font-zed-mono-nerd-font" "--cask"
